[app]
name = "Scoutmaton"
version = "1.0.0-dev"
base_size = [1000, 600]
mode = 2
display_mode = false

[logging]
level = "INFO"
format = "[%(threadName)s] - %(message)s"

[commands]
[commands.mode]
short = "-m"
long = "--mode"
help = "Modalità di esecuzione: 1 - normale, 2 - debug, 3 - threaded, 4 - threaded debug"
arg = true

[commands.name]
short = "-n"
long = "--name"
help = "Nome dell'applicazione"
arg = true

[commands.fullscreen]
short = "-f"
long = "--fullscreen"
help = "Imposta l'applicazione fullscreen"
arg = false

[commands.deferred]
long = "--deferred"
help = "Ritarda l'avvio della GUI fino a quando non è chiamato un metodo del gui manager"
arg = false

[commands.camera]
short = "-c"
long = "--camera"
help = "Id della fotocamera da usare"
arg = true

[photo]
count = 3
countdown = 3
queue_size = 3
prefix = 'foto_'
extension = 'jpg'

[paths.folders]
logs = "logs"
images = "images"
photos = "photos"

[paths.images]
icon = "icon.png"
watermark = "watermark.png"
background = "background.png"
arrow = "arrow.png"

[gui.labels]
init = "Avvio"
token = "Inserisci un gettone"
button = "Premi il pulsante"
photo_count = "Foto"
pose = "Mettiti in posa!"
print_preview = "Stampa in corso. Attendi..."

[gui.colors]
text = "white"
background = "black"

[io.pins]
[io.pins.button_led]
pin = 23
type = 0 # OUTPUT
pud = 20 # OFF

[io.pins.button]
pin = 24
type = 1
pud = 22

[io.pins.microswitch]
pin = 25
type = 1 # IN
pud = 22 # UP

[usb.printer]
sheet_format = "A5"
dpi = 300
sheet_margins = [0.5, 0.5, 0.5, 0.5] # cm
pics_spacing = 0.5                   # cm
pics_per_row = 2
max_queue = 10
max_wait_sec = 90

[usb.camera]
default = 0
